### ISSUE TITLE
请问这个怎么使用

### ISSUE THREAD

**Issue by iAmSOScArEd** [fuyanQAQ/ios-sky-cheater#1]
RT，请问这个怎么使用啊，可以教一下嘛，谢谢！

**Comment by fuyanQAQ** [comment]
使用xcode编译即可，不过里面的偏移需要更新

**Comment by iAmSOScArEd** [comment]
请问是否有教程或者文档，能够支持我独立更新的～，感谢！
如果您有时间，或者是否可以教一下，在下感激不尽。

**Comment by fuyanQAQ** [comment]
需要自己去通过ce或者igg修改器去获取

**Comment by iAmSOScArEd** [comment]
好的，感谢，我研究一下
